apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orders-app.fullname" . }}-mongodb-user-password
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "orders-app.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  # Пароль будет закодирован в base64 из values.yaml
  password: {{ .Values.mongodb.auth.password | b64enc }}