replicaCount: 1

image:
  api:
    repository: orders-api
    tag: "0.8"
    pullPolicy: IfNotPresent
  logger:
    repository: orders-logger
    tag: "0.8"
    pullPolicy: IfNotPresent

service:
  api:
    port: 8000
    targetPort: 8000

# Новые секции: образы для Mongo / ZooKeeper / Kafka
mongo:
  enabled: true
  image:
    repository: mongo
    tag: "5.0"    # использую 5.x чтобы в контейнере доступна команда `mongo`
    pullPolicy: IfNotPresent
  persistence:
    enabled: false

zookeeper:
  enabled: true
  image:
    repository: confluentinc/cp-zookeeper
    tag: "7.4.0"
    pullPolicy: IfNotPresent
  replicaCount: 1

kafka:
  enabled: true
  image:
    repository: confluentinc/cp-kafka
    tag: "7.4.0"
    pullPolicy: IfNotPresent
  replicaCount: 1
  config:
    # KAFKA_ADVERTISED_LISTENERS будет настроен в шаблонах
    offsetsTopicReplicationFactor: 1

migration:
  enabled: true
  image:
    repository: mongo
    tag: "5.0"
    pullPolicy: IfNotPresent

resources: {}

podAnnotations: {}

logger:
  logPath: /var/log/orders.log
