apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-app.fullname" . }}-api
  labels:
    app: orders-api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: orders-api
