apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "orders-app.fullname" . }}-api
  labels:
    app: orders-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://orders-app-mongodb:27017"
            - name: KAFKA_BROKER
              value: "orders-app-kafka:9092"
          readinessProbe:
            httpGet:
              path: /orders
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

