apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "orders-app.fullname" . }}-api
  labels:
    app: orders-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - containerPort: 8000  # ИЗМЕНИТЬ с 8080 на 8000
          env:
            - name: KAFKA_BROKER
              value: "orders-app-kafka:9092"  # Должно быть правильное имя
            - name: MONGO_USERNAME
              value: "{{ .Values.mongodb.auth.username }}"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "orders-app.fullname" . }}-mongodb-user-password
                  key: password
            - name: MONGO_HOST
              value: "{{ include "orders-app.mongodbServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local"
            - name: MONGO_DATABASE
              value: "{{ .Values.mongodb.database }}"
            - name: APP_NAME
              value: "{{ .Release.Name }}"
          readinessProbe:
            httpGet:
              path: /orders
              port: 8000  # Уже правильно
            initialDelaySeconds: 10  # Увеличить с 5 до 10, чтобы дать время на подключение к MongoDB
            periodSeconds: 10
            timeoutSeconds: 5  # Добавить явный timeout