apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-app.fullname" . }}-mongodb
  labels:
    app: orders-mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: orders-mongodb
