apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "orders-app.fullname" . }}-mongo-migration
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ['sh','-c','until nslookup {{ include "orders-app.mongodbServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local; do echo waiting; sleep 2; done']
      containers:
        - name: migrate
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          command: [ "bash","-lc" ]
          env:
            - name: MONGO_USERNAME
              value: "{{ .Values.mongodb.auth.username }}"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "orders-app.fullname" . }}-mongodb-user-password
                  key: password
          args:
            - |
              echo "Waiting for Mongo to accept connections..."
              # Проверяем доступность с аутентификацией
              until mongo --host {{ include "orders-app.mongodbServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local \
                -u "$MONGO_USERNAME" -p "$MONGO_PASSWORD" --authenticationDatabase admin \
                --eval 'db.adminCommand({ ping: 1 })' > /dev/null 2>&1; do sleep 1; done

              # Выполняем миграцию с аутентификацией
              mongo --host {{ include "orders-app.mongodbServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local \
                -u "$MONGO_USERNAME" -p "$MONGO_PASSWORD" --authenticationDatabase admin \
                ordersdb --eval '
                db.orders.insertMany([
                  {customer: "Ivan", item: "Book", amount: 12.5},
                  {customer: "Anna", item: "Pen", amount: 2.3},
                  {customer: "Sergey", item: "Notebook", amount: 5.0}
                ])
              '
              echo "Migration completed successfully!"