apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orders-app.fullname" . }}-mongodb
  labels:
    app: orders-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-mongodb
  template:
    metadata:
      labels:
        app: orders-mongodb
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: datadir
              mountPath: /data/db
      volumes:
        - name: datadir
          emptyDir: {}
