apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-app.fullname" . }}-zookeeper
  labels:
    app: orders-zookeeper
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
  selector:
    app: orders-zookeeper
